language:
  java
  
jdk:
  - oraclejdk8

branches:
  only:
    - master

os:
    - linux


before_install:
 - wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
 - unzip -qq apache-maven-3.3.9-bin.zip
 - export M2_HOME=$PWD/apache-maven-3.3.9
 - export PATH=$M2_HOME/bin:$PATH

 
jobs:
  include:
    - stage: test
      script: ./runmvnprofile.sh gw4e-eclipse-plugin-tests
    - script: ./runmvnprofile.sh gw4e-eclipse-plugin-ui-tests
    - script: ./runmvnprofile.sh gw4e-eclipse-studio-tests
    - script: ./runmvnprofile.sh gw4e-eclipse-studio-ui-tests