language: java
jdk:
- oraclejdk8
env:
  global:
  - GITHUB_REPO: gw4e/gw4e.project
  - GIT_NAME: Travis CI
  - GIT_EMAIL: builds@travis-ci.org
  - GIT_BRANCH: master
  - ENCRYPTION_LABEL: ccd276b8e5b2
  - secure: "Z2LagKOSXy1Ru3033Lx3G5x0q7bP4cgp2yu/SSoN5qJbfjQYUWV/TWcg59ZmAbuE8/D7bAz14yjRHRv6FAKznrF1oCX51ohsWjoUOQR75Q79eA8oj8FIQqluci25t64W4HdvDSZbLL5/jzjD5G9B9ZlMhLsRoKM/uTNC+IM54mEKUSdbHto2yw0Yyr3Y3QZkE4dsFj6mq9hJs9a6pzwH1CGbj6fXBFHx0foWXyAi1DA61H/oLp+8sCe7KmvWu1KaNRKrgLGwsNBBHszxK5joX/UOuKFqN/DxUDOKMGDp0OHGqjTEFPDN50h9/4OZDaSaYcPDWm1z1h0HdZQyfjN4BKKBhknAnRhkAyXp/nGDPROBQEV5px9g4yPB3MF7D7SPwq4eWE8Sm7BI3DsCvTToSF4pkf0dhjnA5w8SC/zq4oDXYAi9FRzgVWjSFEK8u6K2ZsfT65/mOhD1JuMq93kKSO8iP4QJ5m8vD8ghooNkSf1+JKsCKB/kS1ye8/QyHquqbKuOQmt7Oh09sszRLk3J8haeR7kokcwZl+9qXjml9m/cuJW2xuIQXN8KCQAn6sM5dlkCdyFngNoaf4S0UGaQ4XRPy9Xhh4tbPCxxa1ebdgph6r3FTXxG8h5MClStSazd+UuQobKzYrPgt99hag14UFj1gduPlRaw+JHbHzJhcaE="
branches:
  only:
  - master
os:
- linux
dist: trusty
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_ccd276b8e5b2_key -iv $encrypted_ccd276b8e5b2_iv
  -in id_rsa.pub.enc -out $HOME/.ssh/id_rsa.pub -d
- wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip
- unzip -qq apache-maven-3.3.9-bin.zip
- export M2_HOME=$PWD/apache-maven-3.3.9
- export PATH=$M2_HOME/bin:$PATH
jobs:
  include:
  - stage: test
    script: ./runmvnprofile.sh gw4e-eclipse-plugin-tests 
  - script: ./runmvnprofile.sh gw4e-eclipse-plugin-ui-tests gw4e-eclipse-plugin-ui-testsPart1
  - script: ./runmvnprofile.sh gw4e-eclipse-plugin-ui-tests gw4e-eclipse-plugin-ui-testsPart2
  - script: ./runmvnprofile.sh gw4e-eclipse-studio-tests
  - script: ./runmvnprofile.sh gw4e-eclipse-studio-ui-tests
  - stage: deploy
    script: ./upload.sh
